import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { SHOTS } from "./screenshot-routes.js";
import type { ReferenceFrame } from "./v9-reference.js";

/**
 * Builds the canonical frame map:
 *
 *   Frame ID -> HTML source -> React route -> state -> reference png -> implementation png
 *
 * Every one of the 86 design frames appears exactly once, whether or not anything has
 * been built for it. A frame with no route is a hole in the migration and must be
 * visible as one — that is the whole point of generating this from data rather than
 * writing it by hand.
 *
 *   pnpm shots:map
 */

const ROOT = process.cwd();
const SHOTS_DIR = join(ROOT, "docs", "migration", "screenshots");

/**
 * Frame -> shot slug. Only records mappings that are REAL: a frame is mapped when a
 * route exists that is meant to render it. Frames whose surface does not exist yet
 * are deliberately absent, so the generated map shows them as unmapped.
 */
const FRAME_TO_SHOT: Record<string, string> = {
  "v9-01": "A1-splash",
  "v9-02": "A2-welcome",
  "v9-03": "A3-phone",
  "v9-04": "A4-otp",
  "v9-05": "A5-otp-error",
  "v9-07": "B1-role",
  "v9-08": "B3-create-1",
  "v9-09": "B6-join",
  "v9-11": "B7-done",
  "v9-13": "C1-home-inchair",
  "v9-21": "D1-consult",
  "v9-32": "E1-patients",
  "v9-33": "E2-search",
  "v9-35": "E4-new-patient",
  "v9-37": "E6-patient-overview",
  "v9-38": "E7-patient-cases",
  "v9-40": "E8-patient-teeth",
  "v9-41": "E10-patient-billing",
  "v9-46": "G1-schedule-day",
  "v9-47": "G2-schedule-multi",
  "v9-50": "H1-today",
  "v9-54": "H5-billing",
  "v9-55": "H6-outstanding",
  "v9-56": "I1-lab",
  "v9-58": "I3-lab-case",
  "v9-59": "I4-lab-new",
  "v9-61": "I6-vendors",
  "v9-62": "J1-messages",
  "v9-65": "J4-lab-inbox",
  "v9-67": "K1-inventory",
  "v9-68": "K2-item",
  "v9-70": "L1-more",
  "v9-72": "L3-whatsapp",
  "v9-73": "L4-availability",
  "v9-74": "L5-dayoff",
  "v9-75": "L6-templates",
};

/** Frames that are app-only screens' counterparts, or intentionally out of scope. */
const OUT_OF_SCOPE: Record<string, string> = {
  "v9-06": "Device unlock — WebAuthn descoped by the owner; PIN deferred",
};

interface Row {
  frame: string;
  name: string;
  section: string;
  source: string;
  reference: string;
  shot: string | null;
  route: string | null;
  role: string | null;
  state: string;
  implementation: string | null;
  status: "mapped" | "unmapped" | "out-of-scope";
}

async function main() {
  const manifest: ReferenceFrame[] = JSON.parse(
    await readFile(join(SHOTS_DIR, "v9-reference", "manifest.json"), "utf8"),
  );

  const rows: Row[] = manifest.map((f) => {
    const slug = FRAME_TO_SHOT[f.id] ?? null;
    const shot = slug ? SHOTS.find((s) => s.slug === slug) : undefined;
    const outOfScope = OUT_OF_SCOPE[f.id];

    return {
      frame: f.id,
      name: f.name,
      section: f.section,
      source: f.source,
      reference: `v9-reference/${f.png}`,
      shot: slug,
      route: shot?.path ?? null,
      role: shot?.role ?? null,
      // v9 draws each state as its OWN frame, so the frame IS the state. What varies
      // is whether the React side can be driven into it.
      state: shot?.prepare ? "driven (prepare step)" : shot ? "default" : "—",
      implementation: slug ? `current/${slug}.png` : null,
      status: outOfScope ? "out-of-scope" : slug ? "mapped" : "unmapped",
    };
  });

  await writeFile(
    join(SHOTS_DIR, "frame-map.json"),
    JSON.stringify(rows, null, 2),
  );

  const mapped = rows.filter((r) => r.status === "mapped");
  const unmapped = rows.filter((r) => r.status === "unmapped");
  const oos = rows.filter((r) => r.status === "out-of-scope");

  const md = [
    "# Frame map — design frame → implementation",
    "",
    "Generated by `pnpm shots:map`. Do not edit by hand.",
    "",
    `**${manifest.length} canonical frames** · ${mapped.length} mapped · ${unmapped.length} unmapped · ${oos.length} out of scope`,
    "",
    "A frame with no route is a hole in the migration. It is listed so it cannot hide.",
    "",
    "| Frame | Name | Source | Route | Role | State | Status |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows.map(
      (r) =>
        `| \`${r.frame}\` | ${r.name} | ${r.source.replace("odovox-", "").replace(".html", "")} | ${r.route ? `\`${r.route}\`` : "—"} | ${r.role ?? "—"} | ${r.state} | ${r.status} |`,
    ),
  ].join("\n");

  await writeFile(join(ROOT, "docs", "migration", "frame-map.md"), md);

  console.log(
    `${manifest.length} frames · ${mapped.length} mapped · ${unmapped.length} UNMAPPED · ${oos.length} out of scope`,
  );
  console.log(`\nUnmapped frames (no React route renders these yet):`);
  for (const r of unmapped) console.log(`  ${r.frame}  ${r.name}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
